spring.application.name=AirBnb

spring.datasource.url=jdbc:postgresql://staylio-db:5432/staylioDB
spring.datasource.username=postgres
spring.datasource.password=data@2601
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api/v1


secret.key =2376432rebdudf2g87b24d6n2928usq9348372by4noqd8rv4c8b7t4vqib746538

frontend.url=http://host.docker.internal:8080

stripe.secret.key=sk_test_sdbffygsfksduygwkuert6734ugrybujaewygakueysdfgduewyrt23evyu6tyvei7qw6edydiyutasfda7s6dyavsd7asd6

stripe.webhook.secret=whsec_chjhghfusdftys87fwegr8f37rtg293r76g23rb9723689rg23
